package aspectlib

import "html/template"

type ProxyData struct {
	Package         string
	Imports         []*ProxyImport
	ProxyStructName string
	Methods         []*ProxyMethod
}

type ProxyMethod struct {
	Name        string
	Params      string
	ParamNames  string
	Results     string
	ResultNames string
	Before      []any
	After       []any
}

type ProxyImport struct {
	Alias template.HTML
	Path  template.HTML
}

const proxyTpl = `
// Code generated by sandwich. DO NOT EDIT.

package {{.Package}}

import (
	{{- range $i, $s := .Imports }}
	{{ $s.Alias}} {{ $s.Path}}
	{{- end}}
)

type {{ .ProxyStructName }}Proxy struct {
	parent *{{ .ProxyStructName }}
}

func New{{ .ProxyStructName }}Proxy(parent *{{ .ProxyStructName }}) *{{ .ProxyStructName }}Proxy {
	return &{{ .ProxyStructName }}Proxy{parent: parent}
}

{{ range .Methods }}
func (p *{{$.ProxyStructName}}Proxy) {{ .Name }} ({{ .Params }}) ({{ .Results }}) {
	{{- range $i, $s := .Before }}
	{{ $s }}
	{{- end }}
	{{- range $i, $s := .After }}
	{{ $s }}
	{{- end }}
	return {{ .ResultNames }}
}
{{ end }}
`

func GetProxyTpl() string {
	return proxyTpl
}
