// Code generated by sandwich. DO NOT EDIT.

package examples

import (
	"context"
	"fmt"

	"github.com/go-park/sandwich/examples/lib"
	"github.com/sirupsen/logrus"
	"gorm.io/gorm"
)

type ServiceProxy struct {
	parent *Service
}

func NewServiceProxy(parent *Service) *ServiceProxy {
	return &ServiceProxy{parent: parent}
}

func (p *ServiceProxy) Foo(ctx context.Context, i int) (r0 interface{}, r1 error) {
	fmt.Println("around before log")
	fmt.Println("params: ", []interface{}{ctx, i})
	fmt.Println("before log")
	println("around before trans")
	err := lib.GetGormDB().Transaction(func(tx *gorm.DB) error {
		println("before trans")
		logrus.WithContext(ctx).WithField("func", "Foo").WithField("args", []interface{}{ctx, i})
		r0, r1 = p.parent.Foo(ctx, i)
		return r1
	})
	r1 = err
	println("around after trans")
	println("after trans")
	fmt.Println("results: ", []interface{}{r0, r1}, r1)
	fmt.Println("around after log")
	fmt.Println("after log")
	return r0, r1
}

func (p *ServiceProxy) Bar(ctx context.Context) (r0 string, r1 error) {
	r0, r1 = p.parent.Bar(ctx)
	return r0, r1
}
